// ── Game constants ────────────────────────────────────────────────────────────

export const HEX_SIZE          = 52;
export const MIN_SCALE         = 0.5;
export const MAX_SCALE         = 2.0;
export const INITIAL_SCALE     = 1.0;
export const AUTOSAVE_MS       = 30_000;
export const WORKER_SPEED      = 95;
export const SAVE_KEY          = 'hexdomain_save';
export const SAVE_VERSION      = 4;
export const HEAL_TIME         = 30;   // seconds to heal at ospedale
export const RESEARCH_GEN_TIME = 5;    // seconds per +1 ricerca tick

// ── Hex types ─────────────────────────────────────────────────────────────────

export const HEX_TYPE = Object.freeze({
  STARTER:      'starter',
  FIELD:        'field',
  QUARRY:       'quarry',
  LAKE:         'lake',
  FOREST:       'forest',
  PASTURE:      'pasture',
  DESERT:       'desert',
  MINE:         'mine',
  RICERCA:      'ricerca',
  CUCINA:       'cucina',
  FABBRO:       'fabbro',
  CASA:         'casa',
  OSPEDALE:     'ospedale',
  FALEGNAMERIA: 'falegnameria',
  CACCIA:       'caccia',
});

export const HEX_COLOR = {
  starter:      '#7a5832',
  field:        '#8c7010',
  quarry:       '#4e3e32',
  lake:         '#103c72',
  forest:       '#0c3818',
  pasture:      '#246018',
  desert:       '#b87018',
  mine:         '#201408',
  ricerca:      '#1a1060',
  cucina:       '#6b2a00',
  fabbro:       '#1c1c1c',
  casa:         '#5c3820',
  ospedale:     '#c0d8e0',
  falegnameria: '#3d2010',
  caccia:       '#1a3a08',
};

export const HEX_LABEL = {
  starter:      'Villaggio',
  field:        'Campo',
  quarry:       'Cava',
  lake:         'Lago',
  forest:       'Bosco',
  pasture:      'Pascolo',
  desert:       'Deserto',
  mine:         'Miniera',
  ricerca:      'Ricerca',
  cucina:       'Cucina',
  fabbro:       'Fabbro',
  casa:         'Casa',
  ospedale:     'Ospedale',
  falegnameria: 'Falegnameria',
  caccia:       'Caccia',
};

// Base types generated by random exploration (not in build menu as "special")
export const RANDOM_HEX_TYPES = [
  'field','quarry','lake','forest','pasture','desert','mine',
];

// Default build types (no research needed)
export const DEFAULT_BUILD_TYPES = [
  'field','quarry','lake','forest','pasture','desert','mine','ricerca',
];

// Special build types (require research to unlock)
export const SPECIAL_HEX_TYPES = [
  'cucina','fabbro','casa','ospedale','falegnameria','caccia',
];

// ── Resources ─────────────────────────────────────────────────────────────────

export const RESOURCE_LIST = [
  'pietra','acqua','grano','legno','carne','sabbia','ferro','mana','ricerca',
  'pane','stufato','mattoni','lingotti',
];

export const RESOURCE_LABEL = {
  pietra:'Pietra', acqua:'Acqua',   grano:'Grano',    legno:'Legno',
  carne:'Carne',   sabbia:'Sabbia', ferro:'Ferro',    mana:'Mana',  ricerca:'Ricerca',
  pane:'Pane',     stufato:'Stufato', mattoni:'Mattoni', lingotti:'Lingotti',
};

export const RESOURCE_ICON = {
  pietra:'🪨', acqua:'💧',  grano:'🌾',  legno:'🪵',
  carne:'🥩',  sabbia:'🏖', ferro:'⚙',  mana:'✨', ricerca:'🔬',
  pane:'🍞',   stufato:'🍲', mattoni:'🧱', lingotti:'🥇',
};

export const HEX_YIELD = {
  starter:      { pietra:2, acqua:2, grano:2, legno:2, carne:1, sabbia:2, ferro:1 },
  field:        { grano:4 },
  quarry:       { pietra:4 },
  lake:         { acqua:4 },
  forest:       { legno:4 },
  pasture:      { carne:3 },
  desert:       { sabbia:4 },
  mine:         { ferro:3 },
  ricerca:      { ricerca:2 },
  caccia:       { carne:4 },
};

// ── Build costs (flat cost per type, shown in build menu) ─────────────────────

export const BUILD_COST = {
  field:        { legno:2, pietra:1 },
  quarry:       { legno:2, pietra:3 },
  lake:         { legno:2, acqua:3 },
  forest:       { legno:4, grano:1 },
  pasture:      { legno:2, grano:3 },
  desert:       { sabbia:4 },
  mine:         { pietra:5, legno:2 },
  ricerca:      { pietra:5, legno:5, mana:1 },
  cucina:       { legno:4, pietra:2, grano:4 },
  fabbro:       { pietra:8, ferro:3, legno:2 },
  casa:         { legno:8, pietra:4 },
  ospedale:     { legno:5, pietra:5, acqua:4 },
  falegnameria: { legno:10, pietra:2 },
  caccia:       { legno:3, carne:2 },
};

// ── Research recipes ──────────────────────────────────────────────────────────

export const RESEARCH_RECIPES = {
  sblocca_cucina:        { cost:{ricerca:5},  time:60,  unlocks:'cucina',       label:'Sblocca Cucina',        desc:'Costruisci una Cucina per produrre cibo lavorato' },
  sblocca_fabbro:        { cost:{ricerca:8},  time:90,  unlocks:'fabbro',       label:'Sblocca Fabbro',        desc:'Costruisci un Fabbro per forgiare metalli' },
  sblocca_casa:          { cost:{ricerca:3},  time:30,  unlocks:'casa',         label:'Sblocca Casa',          desc:'Costruisci una Casa per +1 lavoratore permanente' },
  sblocca_ospedale:      { cost:{ricerca:12}, time:120, unlocks:'ospedale',     label:'Sblocca Ospedale',      desc:'Cura i lavoratori malati' },
  sblocca_falegnameria:  { cost:{ricerca:6},  time:75,  unlocks:'falegnameria', label:'Sblocca Falegnameria',  desc:'Costruisci una Falegnameria per lavorare il legno' },
  sblocca_caccia:        { cost:{ricerca:4},  time:45,  unlocks:'caccia',       label:'Sblocca Caccia',        desc:'Costruisci un Campo di Caccia' },
  velocita_lavoratori:   { cost:{ricerca:15}, time:180, unlocks:'velocita',     label:'Velocità Lavoratori',   desc:'I lavoratori si muovono il 50% più velocemente' },
  automazione:           { cost:{ricerca:20}, time:240, unlocks:'automazione',  label:'Automazione',           desc:'I lavoratori possono essere impostati in modalità automatica' },
  evoluzione_lavoratore: { cost:{ricerca:30}, time:300, unlocks:'evoluzione',   label:'Evolvi Lavoratore',     desc:'Permette di evolvere i lavoratori (velocità ×2)' },
};

// ── Crafting station recipes ──────────────────────────────────────────────────

export const CUCINA_RECIPES = {
  pane_artigianale: { inputs:{grano:3,acqua:1},        output:{pane:4},           time:20, label:'Pane Artigianale' },
  stufato_ricco:    { inputs:{carne:2,acqua:1,grano:2}, output:{stufato:3},        time:30, label:'Stufato Ricco' },
  pasto_misto:      { inputs:{grano:1,carne:1,acqua:1}, output:{pane:1,stufato:1}, time:25, label:'Pasto Misto' },
};

export const FABBRO_RECIPES = {
  lingotti_puri:      { inputs:{ferro:3},          output:{lingotti:2},           time:30, label:'Lingotti Puri' },
  mattoni_rinforzati: { inputs:{pietra:3,ferro:1}, output:{mattoni:4},            time:25, label:'Mattoni Rinforzati' },
  lega_preziosa:      { inputs:{ferro:4,mana:1},   output:{lingotti:4},           time:45, label:'Lega Preziosa' },
};

export const FALEGNAMERIA_RECIPES = {
  assi:      { inputs:{legno:4},          output:{mattoni:2},            time:20, label:'Assi da Costruzione' },
  mobili:    { inputs:{legno:6,pietra:1}, output:{mattoni:4},            time:35, label:'Mobili' },
  strumenti: { inputs:{legno:4,ferro:2},  output:{lingotti:2,mattoni:1}, time:40, label:'Strumenti' },
};

export const CACCIA_RECIPES = {
  lepre:     { output:{carne:2}, time:20, label:'Lepre 🐇',     desc:'Piccola ma veloce' },
  cervo:     { output:{carne:4}, time:35, label:'Cervo 🦌',     desc:'Alta resa di carne' },
  cinghiale: { output:{carne:6}, time:45, label:'Cinghiale 🐗', desc:'Ottima resa, più lento' },
};

export const CRAFT_RECIPES = {
  cucina:       CUCINA_RECIPES,
  fabbro:       FABBRO_RECIPES,
  falegnameria: FALEGNAMERIA_RECIPES,
  caccia:       CACCIA_RECIPES,
};

// ── Hex grid ──────────────────────────────────────────────────────────────────

export const HEX_DIRS = [
  {q:1,r:0},{q:1,r:-1},{q:0,r:-1},
  {q:-1,r:0},{q:-1,r:1},{q:0,r:1},
];
